import type { Role } from "./types";

/** Newest first. Dates are kept as written on the record, not prettified. */
export const experience: readonly Role[] = [
  {
    id: "zedcrest",
    company: "Zedcrest Group",
    product: "Zedvance — personal & business banking",
    title: "Mobile Engineer",
    employment: "Full-time",
    location: "Lagos, Nigeria",
    start: "Mar 2024",
    end: "Present",
    current: true,
    summary:
      "Built ExtraCash, an embedded lending product inside a live retail banking app — from open-banking underwriting through to disbursement and card repayment — plus the POS and business-banking surfaces around it.",
    highlights: [
      "Drove loan eligibility from open-banking statement analysis (Mono), KYC and employment/income capture, with automated decisioning and re-assessment when income changes.",
      "Shipped the full money path: instant disbursement to wallets, repayment by debit card via Rave/Flutterwave, OTP and email verification, KYC-tier gating.",
      "Built a Flutter POS application driving a native Java/Kotlin card SDK over Platform Channels for card-present payments.",
      "Extended the core banking app with cable, electricity and advanced search modules, and built a separate business-banking app for SMEs.",
    ],
    stack: ["Flutter", "Dart", "Kotlin", "Java", "Mono", "Flutterwave", "Platform Channels"],
  },
  {
    id: "medpal",
    company: "MedPal",
    product: "MedPal Provider",
    title: "Flutter Engineer",
    employment: "Contract",
    location: "Remote",
    start: "Jun 2025",
    end: "Present",
    current: true,
    summary:
      "Provider-side telemedicine: real-time consultations on Agora RTC, AI-assisted onboarding, payouts, and a bilingual codebase kept honest by CI.",
    highlights: [
      "Built provider-to-patient video and voice consultations on the Agora RTC engine, modelling the full session lifecycle from incoming request to completion.",
      "Integrated Firebase AI (Vertex AI / Gemini) to suggest a provider’s medical specialty during onboarding — suggested, then confirmed, never inferred silently.",
      "Delivered earnings and payouts, availability scheduling, QR generation, biometric login and document/consent capture.",
      "Led English/Spanish internationalisation: 480+ user-facing strings migrated to gen-l10n with CI parity tests that fail the build on locale drift.",
    ],
    stack: ["Flutter", "Cubit / flutter_bloc", "go_router", "get_it", "Agora RTC", "Firebase AI", "Clean Architecture"],
  },
  {
    id: "snappay",
    company: "SnapPay",
    title: "Flutter Engineer",
    employment: "Contract",
    location: "Remote — Nigeria",
    start: "Apr 2026",
    end: "Jun 2026",
    summary:
      "Feature delivery on a live Nigerian fintech app, and the AES-encrypted transport layer everything else rides on.",
    highlights: [
      "Shipped wallets, transfers, airtime/data/electricity payments, group and personal savings, invoices, QR pay, ticketing and rewards — backwards-compatible and feature-flag-gated to live users.",
      "Engineered an AES-encrypted networking layer with request/response encryption, single-flight key refresh-and-replay on HTTP 403, and session teardown on 401.",
      "Integrated Prembly KYC (BVN / NIN / liveness), biometric auth, QR scan-to-pay, PDF receipts and deep linking on a layered MVVM core.",
      "Decomposed the codebase into modular, AI-loadable skill documents so agents could work inside a live production app safely.",
    ],
    stack: ["Flutter", "MVVM", "Provider", "get_it", "dartz", "AES", "Prembly"],
  },
  {
    id: "equivator",
    company: "Equivator",
    product: "Uplines",
    title: "Senior Frontend Developer",
    employment: "Contract",
    location: "Saudi Arabia — Remote",
    start: "Oct 2024",
    end: "May 2025",
    summary: "Web and mobile delivery on the Uplines platform, including native iOS widgets and the analytics that told us whether any of it worked.",
    highlights: [
      "Built native iOS widgets in Swift/SwiftUI — daily active users up 10%, engagement up 20% off the back of the surrounding UX work.",
      "Instrumented Firebase and CleverTap analytics, cutting the loop time on product decisions by roughly a third.",
      "Shipped gift points, tutorials and onboarding; drove crash triage through Sentry and Crashlytics for a ~30% stability improvement.",
    ],
    stack: ["Swift", "SwiftUI", "Flutter", "Firebase", "CleverTap", "Sentry"],
  },
  {
    id: "max",
    company: "MAX",
    product: "PAMS Mobile · Falcon",
    title: "Flutter Mobile Developer",
    employment: "Full-time",
    location: "Lagos, Nigeria",
    start: "Mar 2024",
    end: "Dec 2024",
    summary: "Mobility platform work — a legacy re-architecture, a multilingual field app, and a live operations map.",
    highlights: [
      "Re-architected a legacy codebase onto Clean Architecture, cutting defects by ~60% and making the thing extensible again.",
      "Built a multilingual testing app with voice playback, widening access for riders across language groups.",
      "Built Falcon’s real-time map interface tracking riders and drivers with live geolocation, speed and distance.",
    ],
    stack: ["Flutter", "Dart", "Clean Architecture", "Maps", "Geolocation"],
  },
  {
    id: "creative-advanced",
    company: "Creative Advanced Technologies",
    product: "Tamata · Taza",
    title: "Flutter Mobile Developer",
    employment: "Contract",
    location: "Dubai, United Arab Emirates",
    start: "Jun 2022",
    end: "Aug 2024",
    summary: "E-commerce at half a million users, and the delivery pipeline that let a small team ship to them without fear.",
    highlights: [
      "Drove a ~40% performance gain and ~25% UX improvement in an app serving 500,000+ users through RxBloc restructuring and targeted profiling.",
      "Stood up a Bitrise CI/CD pipeline and led code review and task tracking — release time halved, ~90% build success rate.",
      "Integrated Shorebird code push, cutting deployment time ~70% and letting fixes reach users without a store round-trip.",
    ],
    stack: ["Flutter", "RxBloc", "Bitrise", "Shorebird", "Jira", "Bitbucket"],
  },
  {
    id: "platnova",
    company: "Platnova",
    title: "Flutter Mobile Developer",
    employment: "Full-time",
    location: "Lagos, Nigeria",
    start: "Oct 2023",
    end: "Apr 2024",
    summary: "Multi-currency wallet work — the first time I had to think hard about money in more than one denomination at once.",
    highlights: [
      "Built a multi-currency wallet handling 5,000+ monthly transactions with Paystack integration.",
      "Led UI work including dark mode and design-review contributions that lifted retention.",
      "Kept the app healthy: dependency upgrades and critical-issue triage.",
    ],
    stack: ["Flutter", "Dart", "Paystack"],
  },
  {
    id: "firstbank",
    company: "First Bank of Nigeria",
    product: "LitApp",
    title: "Flutter Mobile Developer",
    employment: "Contract",
    location: "Lagos, Nigeria",
    start: "Feb 2022",
    end: "Jan 2024",
    summary: "Core retail banking at one of Nigeria’s oldest banks — transfers, airtime, bills, and the scrutiny that comes with the name on the door.",
    highlights: [
      "Built self-transfer, inter/intra-bank transfers, airtime and bill payments into a multifunctional banking app.",
      "Worked closely with UI/UX on design feedback loops — session duration up ~30%, retention up ~15%.",
      "Delivered inside a regulated, cross-functional environment with formal review gates.",
    ],
    stack: ["Flutter", "Dart", "Git"],
  },
  {
    id: "studentpaddy",
    company: "Student Paddy",
    title: "Lead Mobile Developer",
    employment: "Full-time",
    location: "Lagos, Nigeria",
    start: "Jun 2021",
    end: "Jun 2022",
    summary: "My first time owning a product end to end, and my first time being the person other engineers asked.",
    highlights: [
      "Led development of an educational social app across iOS and Android in Flutter.",
      "Built real-time in-app chat and drove engagement through Firebase push notifications and deep linking.",
    ],
    stack: ["Flutter", "Firebase", "Deep linking"],
  },
  {
    id: "algorism",
    company: "Algorism Limited",
    product: "RealtyProx · TaskProx",
    title: "Software Developer Intern",
    employment: "Internship",
    location: "Lagos, Nigeria",
    start: "May 2021",
    end: "Nov 2021",
    summary: "Where it started: real-estate bidding, and learning that reusable widgets are a design decision, not a tidiness one.",
    highlights: [
      "Designed a real-time bidding system for property sales.",
      "Built the reusable component layer the rest of the app was assembled from.",
    ],
    stack: ["Flutter", "Dart"],
  },
];
